spring.application.name=agroslot

spring.datasource.url=jdbc:postgresql://localhost:5432/agroslot_db
spring.datasource.username=agroslot_user
spring.datasource.password=agroslot_pass_dev

# O banco já foi criado pelo schema.sql, então o Hibernate só CONFERE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=agroslot.images